sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t adminprakashdale/chathub -f ./src/chathub/Dockerfile .

# aws deployment settings.
deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "Assistant"
  env: "Assistant-env"
  bucket_name: "elasticbeanstalk-eu-north-1-334562901741"
  bucket_path: "Assistant"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

