# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  chathub:
    image: chathub
    build:
      context: .
      dockerfile: src/chathub/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5112:5112
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
