version: '3.4'

services:
  backoffice:
    image: backoffice
    build:
      context: backoffice
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
  chathub:
    image: chathub
    build:
      context: .
      dockerfile: ./chathub/Dockerfile
    ports:
      - 5112:5112
